### ISSUE TITLE
Смена фона(бэкграунда)

### ISSUE THREAD

**Issue by DarkAssassinUA** [kaba99/cytube-enhanced#1]
Как я понял, url изображения закодирован в base64.Раскодировать не удалось.

**Comment by kaba99** [comment]
http://i.imgur.com/sfWLuJS.png

**Comment by DarkAssassinUA** [comment]
Спасибо, но интересовала возможность смена бэкграунда а не само изображение.
_
Разобрался, закодировал свое изображение в base64 и заменил.
